// Posts from vold.missio.io/blog (article bodies live in src/content/blog-posts.json, keyed by slug). `featured: true` puts a post in the spotlight at the top of the blog page
// (the first featured post leads). Categories are our own grouping for the filters: the source only tags a few posts.

export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  image: string;
  date: string; // ISO, yyyy-mm-dd
  category: Category;
  readMins: number;
  featured: boolean;
};

export const categories = ["Technology", "Fundraising", "Donors", "Marketing", "Stories", "Leadership"] as const;
export type Category = (typeof categories)[number];

export const AUTHOR = "Ria N";
export const postHref = (slug: string) => `/blog/${slug}`;
export const getPost = (slug: string) => posts.find((p) => p.slug === slug);
export const formatDate = (iso: string) =>
  new Date(`${iso}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });

export const posts: Post[] = [
  {
    slug: "top-7-crm-integrations-for-nonprofits-in-2025-with-real-world-use-cases",
    title: "Top 7 CRM Integrations for Nonprofits in 2025 (With Real-World Use Cases)",
    excerpt: "In 2025 platforms like Missio, nonprofits can simplify their operations by having everything in one place.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/5208eecfd415e6ed4db65319a60f1ee7.jpg",
    date: "2023-03-04",
    category: "Technology",
    readMins: 4,
    featured: true,
  },
  {
    slug: "revolutionizing-impact-the-future-of-ai-for-nonprofits-in-2025",
    title: "Revolutionizing Impact: The Future of AI for Nonprofits in 2025",
    excerpt: "As we look ahead to the year 2025, nonprofits are poised to transform their impact through the power of Artificial Intelligence (AI) and innovative technology solutions. AI for nonprofits is no longer a futuristic concept but a present reality that is reshaping the way organizations operate, engage with communities, and achieve their missions.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/111f89029d3d21af19184b72dab8555a.webp",
    date: "2025-01-05",
    category: "Technology",
    readMins: 2,
    featured: true,
  },
  {
    slug: "what-is-donor-management-software",
    title: "What is Donor Management Software?",
    excerpt: "Donor management software is a technology/tool that helps NGOs in maintaining and analyzing donor data in order to comprehend and improve their connections with both new and current donors.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/51307aec5e3df93b253c512a22776cbf.webp",
    date: "2024-08-30",
    category: "Technology",
    readMins: 3,
    featured: true,
  },
  {
    slug: "9-nonprofit-email-marketing-campaigns-ideas",
    title: "9 Nonprofit Email Marketing Campaigns Ideas",
    excerpt: "Email marketing has become a powerful tool for nonprofit organizations, particularly since the pandemic halted many traditional outreach and fundraising tactics. While it may appear to be an outmoded channel in comparison to social media, email has over 4.25 billion users worldwide, with 96% checking their inboxes daily. In this context, it's easy to see why nonprofit professionals are relying on email marketing to increase engagement and donations.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/162dc12dcc8cf529bc37e066e5b6a9ba.webp",
    date: "2024-08-29",
    category: "Marketing",
    readMins: 5,
    featured: true,
  },
  {
    slug: "surrender-them-to-me",
    title: "Surrender Them To Me",
    excerpt: "The birth of my son was a miracle for both of us. His premature arrival at 23 weeks gestation and 1lb 4 ozs ushered us into the uncertainty regarding his life, my life, and even my husband's life. The average nonprofit uses three - five tools to manage their donors, volunteers and outreach activities.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/ff59170754fca47c42d588fa5e5c1475.webp",
    date: "2023-03-04",
    category: "Stories",
    readMins: 4,
    featured: true,
  },
  {
    slug: "5-strategies-for-nonprofit-fundraisers-to-increase-donations",
    title: "5 Strategies for Nonprofit Fundraisers to Increase Donations",
    excerpt: "You may experience occasional stuttering in your fundraising as a professional in the nonprofit sector. You might be going through a fundraising lull in the summer. Or perhaps you've expended a lot of energy enlisting new donors and interacting with current ones, but your fundraising efforts aren't producing the outcomes you were hoping for.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/54a36a3486fd65544b6c6a984f3164bb.webp",
    date: "2024-08-29",
    category: "Fundraising",
    readMins: 7,
    featured: true,
  },
  {
    slug: "5-quick-things-you-can-do-right-away-to-boost-your-year-end-appeals",
    title: "5 quick things you can do right away to boost your year-end appeals",
    excerpt: "Are you currently under fundraising stress? Here are some ideas for boosting your year-end appeal.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/4f08f670cd14f2c377e4285a91bb5526.webp",
    date: "2024-08-29",
    category: "Fundraising",
    readMins: 4,
    featured: false,
  },
  {
    slug: "5-key-components-to-consider-to-market-your-goal-based-campaigns",
    title: "5 key components to consider to market your Goal based campaigns",
    excerpt: "A marketing goal is a specific and measurable objective / goals that helps you in meeting your overall business objectives. It can vary from generating high-quality leads and increasing brand awareness to increasing customer value and referral rate.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/d7491c2f1278720b64a8a9cbf0ecefbf.webp",
    date: "2024-08-29",
    category: "Fundraising",
    readMins: 3,
    featured: false,
  },
  {
    slug: "4-crucial-donor-outreach-techniques-that-go-beyond-solicitations",
    title: "4 Crucial Donor Outreach Techniques That Go Beyond Solicitations",
    excerpt: "Donors are essential to the success of your organization, so you don't want them to view you as their persistent friend who constantly begs for money. The ideal donor relationship should mix donation correspondence with other chances for supporters to become involved.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/494b46e14da7b97171fa264858e4009a.webp",
    date: "2024-08-28",
    category: "Donors",
    readMins: 4,
    featured: false,
  },
  {
    slug: "10-myths-about-saas",
    title: "10 Myths About Saas",
    excerpt: "Software as a Service (SaaS) has revolutionized the way businesses access and use software applications.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/10a5caff0e142a7e6ab8a272a2bfbc80.webp",
    date: "2024-08-13",
    category: "Technology",
    readMins: 1,
    featured: false,
  },
  {
    slug: "the-art-of-storytelling-an-effective-strategy-for-nonprofits",
    title: "The Art of Storytelling: An Effective Strategy for Nonprofits",
    excerpt: "Storytelling is an art, and for nonprofits, it's a tool of immense power. It's a way to connect, engage, and inspire. By mastering this art, nonprofits can amplify their impact and create ripples of positive change.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/ad14a61fc3915ebd426575234a14df2b.webp",
    date: "2023-08-14",
    category: "Marketing",
    readMins: 3,
    featured: true,
  },
  {
    slug: "key-differences-between-strategic-and-operational-plans",
    title: "Key Differences between Strategic and Operational Plans",
    excerpt: "Strategic and operational plans are essential components of effective business management, each serving distinct purposes within an organization. Strategic plans focus on long-term goals and visions, outlining the overall direction and priorities for future growth. In contrast, operational plans are more tactical, detailing the day-to-day activities and processes required to achieve the strategic objectives.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/fc91c28b027f53092aaf3d00940aab30.webp",
    date: "2023-07-20",
    category: "Leadership",
    readMins: 4,
    featured: false,
  },
  {
    slug: "nonprofit-sustainability-how-to-plan-for-long-term-success",
    title: "Nonprofit Sustainability: How to Plan for Long-Term Success",
    excerpt: "Ensuring long-term success for a nonprofit organization requires a comprehensive approach to sustainability. This involves strategic planning, diversifying funding sources, and building strong relationships with stakeholders. By prioritizing adaptability and resilience, nonprofits can navigate challenges and continue making a meaningful impact over time.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/5b3af83c33d668171ffbc1bd1bec3b27.webp",
    date: "2023-06-12",
    category: "Leadership",
    readMins: 4,
    featured: false,
  },
  {
    slug: "grant-writing-tips-for-nonprofits-securing-funding-for-your-cause",
    title: "Grant Writing Tips for Nonprofits: Securing Funding for Your Cause",
    excerpt: "Grants can be a lifeline for nonprofits, providing much-needed funds to carry out their mission. But to secure these funds, organizations must navigate the complex world of grant writing. What does that look like?",
    image: "https://vold.missio.io/user-uploads/public/blog-images/a1ba7baf028492c0c38f35ee3e4838ea.webp",
    date: "2023-06-05",
    category: "Fundraising",
    readMins: 3,
    featured: false,
  },
  {
    slug: "comparing-nonprofit-and-for-profit-organizations-key-differences-uncovered",
    title: "Comparing Nonprofit and For-Profit Organizations: Key Differences Uncovered",
    excerpt: "Nonprofit and for-profit organizations fundamentally differ in terms of their purpose, structure, and financial motivations. Understanding these differences is crucial when deciding the type of organization to start or support. Discover the essential contrasts between nonprofit and for-profit organizations, from their purpose to financial structure and beyond. Gain valuable insights to help you differentiate between these two organizational models and make informed decisions. Let's dive deep into the distinct characteristics of these two types of entities.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/7336145b364e726693153469ab36758d.webp",
    date: "2023-05-15",
    category: "Leadership",
    readMins: 5,
    featured: false,
  },
  {
    slug: "the-importance-of-transparency-in-nonprofit-organizations",
    title: "The Importance of Transparency in Nonprofit Organizations",
    excerpt: "Transparency in nonprofit organizations is more than just a buzzword - it's a fundamental necessity for success. In today's world, potential donors, volunteers, and stakeholders are increasingly seeking organizations that demonstrate openness, accountability, and trustworthiness. In this post, we will explore the importance of transparency in nonprofit organizations, discuss how it contributes to overall success, and offer practical tips for enhancing transparency in your organization.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/d7448a728eda05c7526a9001551c5b73.webp",
    date: "2023-05-08",
    category: "Leadership",
    readMins: 3,
    featured: false,
  },
  {
    slug: "5-ways-for-nonprofits-can-find-new-supporters-in-2023",
    title: "5 Ways for Nonprofits can Find New Supporters in 2023",
    excerpt: "As the nonprofit sector grows increasingly competitive, it is becoming more difficult for organizations to find new supporters who are willing to contribute their time, money, and resources. With the start of 2023, it's time for nonprofits to explore new strategies to expand their supporter base.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/180bb657a409061f4826fba81f5d61b0.webp",
    date: "2023-03-02",
    category: "Donors",
    readMins: 3,
    featured: false,
  },
  {
    slug: "complete-guide-to-cross-sector-partnerships-for-nonprofits",
    title: "Complete Guide to Cross-Sector Partnerships For Nonprofits",
    excerpt: "You don't have to work alone to run your nonprofit. Serving in a cross-sector collaboration with a for-profit company has several advantages and should be incorporated into your organization's strategic plan.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/ae1e4fbfabcbd53f5695571fe92ce259.webp",
    date: "2023-02-08",
    category: "Leadership",
    readMins: 5,
    featured: false,
  },
  {
    slug: "all-you-need-to-know-about-giving-tuesday",
    title: "All You Need To Know About Giving Tuesday",
    excerpt: "Giving Tuesday 2023 will take place on November 28th. Every year, the date is the Tuesday following Thanksgiving. Given that Thanksgiving is in the fourth week of November, Giving Tuesday falls on either the last Tuesday of November or the first Tuesday of December.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/8a7a4e1b965c82d0c4d7787935c3f925.webp",
    date: "2023-01-23",
    category: "Fundraising",
    readMins: 4,
    featured: false,
  },
  {
    slug: "how-to-utilize-social-media-effectively-for-your-nonprofit",
    title: "How to Utilize Social Media Effectively for Your Nonprofit",
    excerpt: "Incorporating social media into your nonprofit's marketing strategy is no longer optional but essential for success. By implementing the strategies outlined in this article, you can effectively utilize social media to raise awareness, connect with your audience, drive engagement, and achieve your nonprofit's goals. Stay consistent, monitor your analytics, and adapt your approach based on audience feedback to ensure long-term success in the ever-evolving landscape of social media.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/a6a14f94846145cb8913689b0d8d8b20.webp",
    date: "2022-07-05",
    category: "Marketing",
    readMins: 4,
    featured: false,
  },
  {
    slug: "migrating-to-the-cloud-a-guide-for-nonprofits",
    title: "Migrating to the Cloud: A Guide for Nonprofits",
    excerpt: "In the 21st century, technology is increasingly becoming the backbone of virtually all operations, even in the nonprofit sector. Cloud migration, a term that seemed esoteric a few years back, is now a common phrase. But what does it mean for nonprofits? And how can it be done effectively? This guide will provide a comprehensive understanding of this process.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/e1aace2f1438ba209ded251514a81a85.webp",
    date: "2022-06-21",
    category: "Technology",
    readMins: 4,
    featured: false,
  },
  {
    slug: "the-benefits-of-volunteering-for-a-nonprofit-and-how-to-get-involved",
    title: "The Benefits of Volunteering for a Nonprofit and How to Get Involved",
    excerpt: "Volunteering for a nonprofit organization can be a transformative experience, enriching your life while positively impacting the lives of others. With countless benefits, from personal development to networking opportunities, it's no wonder that millions of individuals worldwide invest their time and energy in nonprofit work. In this blog, we'll explore the numerous advantages of volunteering for a nonprofit and offer practical guidance on how to get involved.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/80918578b95fd3672d1ccb9985d28c3d.webp",
    date: "2022-05-02",
    category: "Leadership",
    readMins: 3,
    featured: false,
  },
  {
    slug: "the-challenges-of-nonprofit-leadership-and-how-to-overcome-them",
    title: "The Challenges of Nonprofit Leadership and How to Overcome Them",
    excerpt: "Nonprofit leadership is a fulfilling and challenging role that requires passion, creativity, and dedication. Nonprofit leaders are tasked with steering their organizations towards success while managing the unique hurdles they face. This blog aims to discuss these challenges and offer practical solutions to help nonprofit leaders overcome them.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/0065f6d6fb9b5524f1813f727d2d1adb.webp",
    date: "2022-04-28",
    category: "Leadership",
    readMins: 3,
    featured: false,
  },
  {
    slug: "how-to-start-and-run-a-successful-nonprofit-a-complete-guide",
    title: "How to Start and Run a Successful Nonprofit - A Complete Guide",
    excerpt: "Starting and running a successful nonprofit organization can be a rewarding and fulfilling experience. However, it requires a lot of hard work, dedication, and commitment. In this guide, we will discuss the steps involved in starting and running a successful nonprofit organization.",
    image: "https://vold.missio.io/user-uploads/public/blog-images/cb9476ab75d642eb9a178c84504c0793.webp",
    date: "2022-03-23",
    category: "Leadership",
    readMins: 12,
    featured: false,
  },
];
